version: "3.8"

services:
  mongo:
    image: custom-mongo:${IMAGE_TAG}
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: devdb
      MONGO_INITDB_ROOT_PASSWORD: dev@123
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - appnet

  springapp:
    image: springapp:${IMAGE_TAG}
    container_name: springapp
    restart: always
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      MONGO_DB_HOSTNAME: mongo
      MONGO_DB_USERNAME: devdb
      MONGO_DB_PASSWORD: dev@123
    networks:
      - appnet

volumes:
  mongo_data:

networks:
  appnet:
